import { useState } from 'react'
import NumberField from '../ui/NumberField.tsx'
import { DIMENSION_STEP, formatNumber } from '../ui/format.ts'
import type { Board } from '../boards/board.ts'
import type { Furniture } from '../furniture/furniture.ts'
import {
  AXIS_FACES,
  FACES,
  FACE_LABELS,
  anchorRange,
  centeredOffset,
  centeredPairs,
  centeredRange,
  centeredUnit,
  createPullingAnchor,
  faceAxis,
  oppositeFace,
  setAnchorUnit,
  setCenteredOffset,
  setCenteredUnit,
  setTwoSided,
  targetLabel,
  twoSidedProblem,
  upsertAnchor,
  type AnchorConstraint,
  type AnchorTarget,
  type Face,
  type OffsetRange,
  type OffsetUnit,
} from '../layout/constraints.ts'
import { hingeProblem, otherHinge } from '../layout/hinges.ts'

interface Props {
  board: Board
  boards: Board[]
  furniture: Furniture
  constraints: AnchorConstraint[]
  violated: string[]
  onChange: (constraints: AnchorConstraint[]) => void
}

const FURNITURE_TARGET = 'furniture'
/** Fallback limit when the range cannot be computed (invalid joint). */
const OFFSET_LIMIT = 5000

/** Range rounded inwards to the field step, so a clamped value never leaves it. */
function fieldRange(r: OffsetRange | null): OffsetRange {
  if (!r) return { min: -OFFSET_LIMIT, max: OFFSET_LIMIT }
  const min = Math.ceil(r.min / DIMENSION_STEP - 1e-6) * DIMENSION_STEP
  const max = Math.floor(r.max / DIMENSION_STEP + 1e-6) * DIMENSION_STEP
  const fix = (v: number) => Number(v.toFixed(1)) || 0
  return min <= max ? { min: fix(min), max: fix(max) } : { min: fix(r.min), max: fix(r.min) }
}

const rangeText = (r: OffsetRange, unit: OffsetUnit) => `Zakres: ${formatNumber(r.min, 1)} … ${formatNumber(r.max, 1)} ${unit}`

/** mm ↔ % switch next to an offset field. */
function UnitToggle({
  unit,
  label,
  disabled,
  onChange,
}: {
  unit: OffsetUnit
  label: string
  /** No free space to count the percent of – the unit cannot be switched. */
  disabled?: boolean
  onChange: (u: OffsetUnit) => void
}) {
  return (
    <button
      type="button"
      className="small-button constraint-unit"
      data-unit={unit}
      disabled={disabled}
      aria-label={`Jednostka: ${label}`}
      title={
        disabled
          ? 'Brak wolnej przestrzeni – płyta wypełnia mebel w tej osi, nie ma od czego liczyć %'
          : unit === 'mm'
            ? 'Przełącz na % wolnej przestrzeni'
            : 'Przełącz na milimetry'
      }
      onClick={() => onChange(unit === 'mm' ? '%' : 'mm')}
    >
      {unit}
    </button>
  )
}

/**
 * Modes of one joint: HINGE (the board turns around this edge – any board, e.g. an opening top) and
 * TWO-SIDED (both joined boards give way – the gap is shared, `bias` = where it sits between them).
 */
function JointModes({
  c,
  boards,
  constraints,
  managed,
  onChange,
}: {
  c: AnchorConstraint
  boards: Board[]
  constraints: AnchorConstraint[]
  /** Generated by the "Fronty" tool – the modes follow its settings (otwieranie / podwójny). */
  managed: boolean
  onChange: (constraints: AnchorConstraint[]) => void
}) {
  const other = c.hinge ? null : otherHinge(c, constraints)
  const hingeWhy = managed
    ? 'Ustawiane w zakładce Fronty (otwieranie frontu).'
    : c.hinge
      ? null
      : other
        ? `Płyta ma już zawias (${FACE_LABELS[other.face]} → ${targetLabel(other, boards)}) – obraca się wokół jednej osi. Najpierw wyłącz tamten.`
        : hingeProblem(c, boards)
  const twoWhy = managed ? 'Ustawiane w zakładce Fronty (front podwójny).' : c.twoSided ? null : twoSidedProblem(c, boards)
  const set = (patch: Partial<AnchorConstraint>) => onChange(constraints.map((o) => (o.id === c.id ? { ...o, ...patch } : o)))
  return (
    <div className="constraint-modes" data-joint-modes={c.id}>
      <label title={hingeWhy ?? 'Płyta obraca się wokół tej krawędzi (Otwórz / Zamknij na kafelku płyty)'} className={hingeWhy ? 'is-disabled' : undefined}>
        <input type="checkbox" data-field="joint-hinge" checked={!!c.hinge} disabled={!!hingeWhy} onChange={(e) => set({ hinge: e.target.checked || undefined })} />
        zawias
      </label>
      <label title={twoWhy ?? 'Obie płyty ustępują – odsunięcie to szczelina między nimi, dzielona według podziału'} className={twoWhy ? 'is-disabled' : undefined}>
        <input
          type="checkbox"
          data-field="joint-two-sided"
          checked={!!c.twoSided}
          disabled={!!twoWhy}
          onChange={(e) => onChange(setTwoSided(constraints, c.id, e.target.checked, boards))}
        />
        obustronne
      </label>
      {c.twoSided && (
        <label className="constraint-bias" title="Gdzie leży środek szczeliny między dalszymi ścianami obu płyt: 50 % = obie płyty równe">
          podział
          <NumberField
            className="constraint-offset"
            aria-label="Podział obustronnego wiązania [%]"
            data-field="joint-bias"
            min={0}
            max={100}
            step={DIMENSION_STEP}
            scrubStep={1}
            value={Number(((c.bias ?? 0.5) * 100).toFixed(2))}
            disabled={managed}
            onChange={(v) => set({ bias: Number((v / 100).toFixed(4)) })}
          />
          %
        </label>
      )}
    </div>
  )
}

/**
 * "Wiązania" of one board – the 3D ConstraintLayout: every face of the board (lewa / prawa, dolna /
 * górna, tylna / przednia) can be glued to a face of the furniture or of another board with an offset.
 * Boards anchored to this board are listed as dependent – they follow it. A board joined on both of its
 * flat sides (the thickness axis) hangs in the middle between the two planes – such a pair is one row
 * with one value: the distance from that middle (mm) or the position between the planes (%).
 *
 * Offsets are typed as a POSITIVE distance away from the target plane (into the furniture / away from
 * the board / recessed behind an aligned face – see `offsetDirection`), in mm or in % of the free space,
 * and are limited so the board stays inside the furniture (`anchorRange` / `centeredRange`).
 */
export default function ConstraintsFields({ board, boards, furniture, constraints, violated, onChange }: Props) {
  const pair = centeredPairs(constraints, boards).find((p) => p.boardId === board.id) ?? null
  const inPair = new Set(pair ? [pair.min.id, pair.max.id] : [])
  const own = constraints.filter((c) => c.board === board.id && !inPair.has(c.id))
  // two-sided joints made by OTHER boards to this one – this board gives way too, so they are listed here
  const incoming = constraints.filter((c) => c.twoSided && c.target.kind === 'board' && c.target.id === board.id)
  const managed = (c: AnchorConstraint) => !!c.preset && !!boards.find((b) => b.id === c.board)?.front
  const dependent = boards.filter((b) =>
    constraints.some((c) => c.board === b.id && c.target.kind === 'board' && c.target.id === board.id),
  )
  const others = boards.filter((b) => b.id !== board.id)

  const [face, setFace] = useState<Face>('left')
  const [targetId, setTargetId] = useState<string>(FURNITURE_TARGET)
  const target: AnchorTarget = targetId === FURNITURE_TARGET || !others.some((b) => b.id === targetId)
    ? { kind: 'furniture' }
    : { kind: 'board', id: targetId }
  // default target face: the same wall of the furniture / the opposite face of a board (touching faces)
  const defaultTargetFace = (f: Face, t: AnchorTarget) => (t.kind === 'furniture' ? f : oppositeFace(f))
  const [targetFace, setTargetFace] = useState<Face>(defaultTargetFace('left', { kind: 'furniture' }))
  const validTargetFace = faceAxis(targetFace) === faceAxis(face) ? targetFace : defaultTargetFace(face, target)

  const changeFace = (f: Face) => {
    setFace(f)
    setTargetFace(defaultTargetFace(f, target))
  }
  const changeTarget = (id: string) => {
    setTargetId(id)
    setTargetFace(defaultTargetFace(face, id === FURNITURE_TARGET ? { kind: 'furniture' } : { kind: 'board', id }))
  }

  // like a chain in the scene: the new joint pulls the board to the target (offset 0)
  const addAnchor = () =>
    onChange(upsertAnchor(constraints, createPullingAnchor(board, face, target, validTargetFace, boards, furniture)))
  const setOffset = (id: string, offset: number) => onChange(constraints.map((c) => (c.id === id ? { ...c, offset } : c)))
  const setUnit = (id: string, unit: OffsetUnit) => onChange(setAnchorUnit(constraints, id, unit, boards, furniture))
  const pairUnit = pair ? centeredUnit(pair) : 'mm'
  const pairRange = pair ? fieldRange(centeredRange(pair, boards, furniture)) : null
  const remove = (id: string) => onChange(constraints.filter((c) => c.id !== id))
  const removeIds = (ids: string[]) => onChange(constraints.filter((c) => !ids.includes(c.id)))

  return (
    <fieldset className="field constraints" data-section="constraints">
      <legend>
        Wiązania <small>(jak ConstraintLayout, w 3D)</small>
      </legend>
      {pair && (
        <ul className="constraint-list">
          <li
            className={`constraint-row${violated.includes(pair.min.id) ? ' constraint-row--violated' : ''}`}
            data-constraint="centered"
          >
            <span className="constraint-text" title={`Płyta wisi pośrodku między: ${targetLabel(pair.min, boards)} i ${targetLabel(pair.max, boards)}`}>
              <b>{FACE_LABELS[pair.min.face]} ↔ {FACE_LABELS[pair.max.face]}</b> → środek między{' '}
              {targetLabel(pair.min, boards)} i {targetLabel(pair.max, boards)}
            </span>
            <span className="constraint-value" title={pairRange ? rangeText(pairRange, pairUnit) : undefined}>
              <NumberField
                className="constraint-offset"
                aria-label={pairUnit === '%' ? 'Położenie między płaszczyznami [%]' : 'Odsunięcie od środka [mm]'}
                data-field="constraint-offset-centered"
                min={pairRange!.min}
                max={pairRange!.max}
                step={DIMENSION_STEP}
                scrubStep={pairUnit === '%' ? 0.5 : 1}
                value={centeredOffset(pair)}
                onChange={(v) => onChange(setCenteredOffset(constraints, pair, v))}
              />
              <UnitToggle
                unit={pairUnit}
                label="wiązanie środkujące"
                disabled={setCenteredUnit(constraints, pair, pairUnit === 'mm' ? '%' : 'mm', boards, furniture) === constraints}
                onChange={(u) => onChange(setCenteredUnit(constraints, pair, u, boards, furniture))}
              />
            </span>
            <button
              type="button"
              className="small-button small-button--danger"
              aria-label="Usuń wiązanie środkujące"
              onClick={() => removeIds([pair.min.id, pair.max.id])}
            >
              ×
            </button>
          </li>
        </ul>
      )}
      {pair && (
        <p className="field-hint">
          {pairUnit === '%'
            ? 'Płyta jest przyciągana z dwóch stron. Wartość obok to jej położenie między płaszczyznami: 0 % = przy pierwszej (lewa / dolna / tylna), 50 % = pośrodku, 100 % = przy drugiej.'
            : 'Płyta jest przyciągana z dwóch stron, więc stoi pośrodku. Wartość obok odsuwa ją od tego środka (+ w prawo / w górę / do przodu).'}
        </p>
      )}
      {own.length === 0 && !pair ? (
        <p className="field-hint">Płyta nie ma wiązań – nie reaguje na zmiany mebla ani innych płyt.</p>
      ) : (
        <ul className="constraint-list">
          {own.map((c) => {
            const bad = violated.includes(c.id)
            const unit = c.unit ?? 'mm'
            const range = fieldRange(anchorRange(c, constraints, boards, furniture))
            return (
              <li key={c.id} className={`constraint-row${bad ? ' constraint-row--violated' : ''}`} data-constraint={c.face}>
                <span
                  className="constraint-text"
                  title={`${FACE_LABELS[c.face]} → ${targetLabel(c, boards)}${bad ? ' – wiązanie niespełnione' : ''}`}
                >
                  <b>{FACE_LABELS[c.face]}</b> {c.twoSided ? '↔' : '→'} {targetLabel(c, boards)}
                  {c.hinge && <small className="hinge-badge" title="Zawias – płyta obraca się wokół tej krawędzi"> zawias</small>}
                </span>
                <span className="constraint-value" title={rangeText(range, unit)}>
                  <NumberField
                    className="constraint-offset"
                    aria-label={`Odsunięcie wiązania ${FACE_LABELS[c.face]} [${unit}]`}
                    data-field={`constraint-offset-${c.face}`}
                    min={range.min}
                    max={range.max}
                    step={DIMENSION_STEP}
                    scrubStep={unit === '%' ? 0.5 : 1}
                    value={c.offset}
                    onChange={(v) => setOffset(c.id, v)}
                  />
                  <UnitToggle
                    unit={unit}
                    label={`wiązanie ${FACE_LABELS[c.face]}`}
                    disabled={setAnchorUnit(constraints, c.id, unit === 'mm' ? '%' : 'mm', boards, furniture) === constraints}
                    onChange={(u) => setUnit(c.id, u)}
                  />
                </span>
                <button type="button" className="small-button small-button--danger" aria-label={`Usuń wiązanie ${FACE_LABELS[c.face]}`} onClick={() => remove(c.id)}>
                  ×
                </button>
                <JointModes c={c} boards={boards} constraints={constraints} managed={managed(c)} onChange={onChange} />
              </li>
            )
          })}
        </ul>
      )}
      {incoming.length > 0 && (
        <ul className="constraint-list" data-section="two-sided-incoming">
          {incoming.map((c) => {
            const other = boards.find((b) => b.id === c.board)
            const range = fieldRange(anchorRange(c, constraints, boards, furniture))
            return (
              <li key={c.id} className={`constraint-row${violated.includes(c.id) ? ' constraint-row--violated' : ''}`} data-constraint={`in-${c.targetFace}`}>
                <span className="constraint-text" title="Obustronne wiązanie innej płyty – ta płyta też ustępuje">
                  <b>{FACE_LABELS[c.targetFace]}</b> ↔ {other?.name ?? '?'} · {FACE_LABELS[c.face]} <small>(obustronne)</small>
                </span>
                <span className="constraint-value" title={rangeText(range, 'mm')}>
                  <NumberField
                    className="constraint-offset"
                    aria-label={`Szczelina obustronnego wiązania [mm]`}
                    data-field={`constraint-offset-in-${c.targetFace}`}
                    min={range.min}
                    max={range.max}
                    step={DIMENSION_STEP}
                    scrubStep={1}
                    value={c.offset}
                    onChange={(v) => setOffset(c.id, v)}
                  />
                  <span className="constraint-unit-static">mm</span>
                </span>
                <button type="button" className="small-button small-button--danger" aria-label="Usuń obustronne wiązanie" onClick={() => remove(c.id)}>
                  ×
                </button>
                <JointModes c={c} boards={boards} constraints={constraints} managed={managed(c)} onChange={onChange} />
              </li>
            )
          })}
        </ul>
      )}
      {own.some((c) => violated.includes(c.id)) && (
        <p className="field-error">Część wiązań jest niespełniona – są sprzeczne albo płyta nie mieści się w meblu.</p>
      )}
      {dependent.length > 0 && (
        <p className="field-hint">Zależne od tej płyty: {dependent.map((b) => b.name).join(', ')}</p>
      )}

      <div className="constraint-add">
        <select aria-label="Ściana płyty" value={face} onChange={(e) => changeFace(e.target.value as Face)}>
          {FACES.map((f) => (
            <option key={f} value={f}>{FACE_LABELS[f]}</option>
          ))}
        </select>
        <span>→</span>
        <select aria-label="Cel wiązania" value={target.kind === 'furniture' ? FURNITURE_TARGET : target.id} onChange={(e) => changeTarget(e.target.value)}>
          <option value={FURNITURE_TARGET}>Mebel</option>
          {others.map((b) => (
            <option key={b.id} value={b.id}>{b.name}</option>
          ))}
        </select>
        <select aria-label="Ściana celu" value={validTargetFace} onChange={(e) => setTargetFace(e.target.value as Face)}>
          {AXIS_FACES[faceAxis(face)].map((f) => (
            <option key={f} value={f}>{FACE_LABELS[f]}</option>
          ))}
        </select>
        <button type="button" className="small-button" onClick={addAnchor}>Dodaj</button>
      </div>
      <p className="field-hint">
        Nowe wiązanie przyciąga płytę do wskazanej ściany (odsunięcie 0) – tak samo jak łańcuch w scenie.
        Odsunięcie ustawia się potem w polu obok wiązania: wartość dodatnia odsuwa płytę od celu (do wnętrza
        mebla, od sąsiedniej płyty, cofa za lico płyty wyrównanej). <b>mm</b> / <b>%</b> przełącza jednostkę:
        % wolnej przestrzeni – 0 % przy celu, 100 % przy przeciwległej ścianie mebla. Zakres jest ograniczony
        tak, by płyta nie wyszła poza mebel.
      </p>
      <p className="field-hint">
        <b>zawias</b> – płyta obraca się wokół krawędzi tego wiązania (krawędź płyty złączona z płytą prostopadłą
        albo ze ścianą mebla), np. drzwi, klapa, otwierany blat. <b>obustronne</b> – między dwiema płytami zwróconymi
        do siebie: odsunięcie to szczelina, którą obie płyty dzielą według <b>podziału</b> (50 % = po równo), np.
        skrzydła frontu podwójnego.
      </p>
    </fieldset>
  )
}
