import { furnitureSize, type Furniture } from '../furniture/furniture.ts'
import { boardBounds, boardSizeMm, dimensionAxis, type Board, type BoardDimension, type BoardPosition } from '../boards/board.ts'

/**
 * Layout constraints (wiązania) – a 3D analogue of Android's ConstraintLayout.
 *
 * Every board is an axis-aligned box, so it has 6 faces (anchors), two per axis:
 *   X: left / right · Y: bottom / top · Z: back / front
 * An anchor constraint glues one face of a board to a face (on the same axis) of the furniture or of
 * another board, with an offset (odsunięcie):
 *
 *     face(board) = face(target) + raw offset    [mm, along the positive axis direction]
 *
 * The offset the user types is NOT the raw axis value – it is a distance with a sign that means the same
 * thing on every face (see `offsetDirection`): POSITIVE = the board moves away from the target plane
 * into the free space – into the furniture from its wall, away from the board it touches, recessed
 * behind the face of the board it is aligned with. It is given in millimetres or in percent of the
 * free space (`unit: '%'`, see `freeLimitValue`): 0 % = at the target plane, 100 % = at the opposite
 * furniture wall. So no joint needs a negative value any more, and the panel limits the value so the
 * board does not leave the furniture (`anchorRange`).
 *
 * All constraints are linear, so they are solved with Cassowary (the algorithm behind ConstraintLayout
 * and iOS Auto Layout) – see `solver.ts`.
 *
 * Direction matters only for editing: the constrained `board` is the dependent side of the joint. When
 * the user edits a board, the offsets of ITS OWN anchors are re-derived from the new geometry (like a
 * changed margin), while boards anchored TO it follow it (see `rederiveOffsets`).
 */
export type Face = 'left' | 'right' | 'bottom' | 'top' | 'back' | 'front'

export type AnchorTarget = { kind: 'furniture' } | { kind: 'board'; id: string }

/** Unit of an anchor offset: millimetres or percent of the free space (see `freeLimitValue`). */
export type OffsetUnit = 'mm' | '%'

export interface AnchorConstraint {
  id: string
  /** Constrained (dependent) board. */
  board: string
  face: Face
  target: AnchorTarget
  /** Face of the target – always on the same axis as `face`. */
  targetFace: Face
  /**
   * Offset (odsunięcie) in `unit`: positive = away from the target plane into the free space (see
   * `offsetDirection`). Changed only in the panel. The raw axis value is given by `anchorRawOffset`.
   */
  offset: number
  /** Unit of `offset` – millimetres (default) or percent of the free space. */
  unit?: OffsetUnit
  /**
   * Geometry of the dependent board just before this joint was made. Removing the joint puts the board
   * back where it was (on that axis), once no other joint holds it there – see `restoreAfterRemoval`.
   */
  restore?: BoardGeometry
  /**
   * Joint generated by the predefined carcass boards (`carcass/carcass.ts`) from the relations between
   * them (dach nałożony / między bokami …). It is an ordinary joint – its offset can be changed in the
   * panel and a chain can replace it – but it is regenerated when the carcass relations change.
   */
  preset?: boolean
  /**
   * Second target: the plane of the joint is then the MIDDLE between `target.targetFace` and
   * `target2.targetFace2` (both on the same axis) – e.g. the meeting line of the two leaves of a double
   * front sits in the middle of the opening, whatever its size (see `anchorTargetValue`).
   */
  target2?: AnchorTarget
  targetFace2?: Face
  /**
   * HINGE mode (tryb zawiasu): the board turns around the edge of this face when it is opened – any board
   * (a door, a flap, an opening top …), see `layout/hinges.ts`. Allowed on an edge face of the board (not
   * on its flat sides) joined to a PERPENDICULAR board or to a furniture wall. Geometry-wise the joint
   * stays an ordinary joint – the turn is shown in the scene only.
   */
  hinge?: boolean
  /**
   * TWO-SIDED joint (obustronne – like a chain in ConstraintLayout): a joint between two boards facing each
   * other (e.g. the right face of one leaf ↔ the left face of the other). Both boards give way: the offset
   * is the gap between them and the gap sits at `bias` of the span between their far faces – so a
   * bigger gap takes half from each (at bias 0.5), and both follow when the span changes. See
   * `twoSidedParts` / the solver.
   */
  twoSided?: boolean
  /** Two-sided joint: where the middle of the gap is between the far faces of the two boards (0–1, default 0.5). */
  bias?: number
  /**
   * Part of `offset` [mm] that comes from the fronts (a carcass / shelf set back behind an overlay or
   * inset front – `fronts/fronts.ts`); kept separately so the user's own setback is not lost when the
   * fronts change.
   */
  recess?: number
}

/** Position + the two changeable dimensions of a board (the thickness never changes). */
export interface BoardGeometry {
  position: BoardPosition
  width: number
  height: number
}

export const boardGeometry = (b: Board): BoardGeometry => ({ position: { ...b.position }, width: b.width, height: b.height })

export type Axis = 0 | 1 | 2

export const FACES: Face[] = ['left', 'right', 'bottom', 'top', 'back', 'front']

/** Face → [axis, side] (side 0 = min, 1 = max). */
export const FACE_INFO: Record<Face, [Axis, 0 | 1]> = {
  left: [0, 0],
  right: [0, 1],
  bottom: [1, 0],
  top: [1, 1],
  back: [2, 0],
  front: [2, 1],
}

export const FACE_LABELS: Record<Face, string> = {
  left: 'lewa',
  right: 'prawa',
  bottom: 'dolna',
  top: 'górna',
  back: 'tylna',
  front: 'przednia',
}

/** The two faces of an axis: [min, max]. */
export const AXIS_FACES: Record<Axis, [Face, Face]> = {
  0: ['left', 'right'],
  1: ['bottom', 'top'],
  2: ['back', 'front'],
}

/** Contact tolerance [mm] – faces closer than this are considered touching. */
export const CONTACT_EPS = 0.05

/** Smallest size [mm] of a board along any axis (also used by the solver). */
export const MIN_BOARD_SIZE = 1

const roundMm = (v: number) => Number(v.toFixed(3)) || 0

export const faceAxis = (f: Face): Axis => FACE_INFO[f][0]
export const oppositeFace = (f: Face): Face => {
  const [axis, side] = FACE_INFO[f]
  return AXIS_FACES[axis][side ? 0 : 1]
}

/** Coordinate [mm] of a board face in the furniture coordinate system. */
export function boardFaceValue(board: Board, face: Face): number {
  const [axis, side] = FACE_INFO[face]
  const b = boardBounds(board)
  return side ? b.max[axis] : b.min[axis]
}

/** Coordinate [mm] of a furniture face (min faces = 0, max faces = furniture size). */
export function furnitureFaceValue(furniture: Furniture, face: Face): number {
  const [axis, side] = FACE_INFO[face]
  return side ? furnitureSize(furniture)[axis] : 0
}

/** Coordinate of the anchor target face, or null when the target board does not exist. */
export function targetFaceValue(target: AnchorTarget, face: Face, boards: Board[], furniture: Furniture): number | null {
  if (target.kind === 'furniture') return furnitureFaceValue(furniture, face)
  const b = boards.find((o) => o.id === target.id)
  return b ? boardFaceValue(b, face) : null
}

/**
 * Coordinate of the plane an anchor is glued to: the target face, or the middle between the two target
 * faces of a joint with `target2`. Null when a target board does not exist.
 */
export function anchorTargetValue(
  c: Pick<AnchorConstraint, 'target' | 'targetFace' | 'target2' | 'targetFace2'>,
  boards: Board[],
  furniture: Furniture,
): number | null {
  const a = targetFaceValue(c.target, c.targetFace, boards, furniture)
  if (a === null || !c.target2 || !c.targetFace2) return a
  const b = targetFaceValue(c.target2, c.targetFace2, boards, furniture)
  return b === null ? null : (a + b) / 2
}

/** Structural validity: both faces on the same axis, target exists and is not the board itself. */
export function isAnchorValid(c: AnchorConstraint, boards: Board[]): boolean {
  if (faceAxis(c.face) !== faceAxis(c.targetFace)) return false
  if (!boards.some((b) => b.id === c.board)) return false
  if (c.target2) {
    if (!c.targetFace2 || faceAxis(c.targetFace2) !== faceAxis(c.face)) return false
    if (c.target2.kind === 'board') {
      const id2 = c.target2.id
      if (id2 === c.board || !boards.some((b) => b.id === id2)) return false
    }
  }
  if (c.target.kind === 'board') return c.target.id !== c.board && boards.some((b) => b.id === (c.target as { id: string }).id)
  return true
}

// ---- offsets: direction, unit, limits -------------------------------------------------------

type AnchorFaces = Pick<AnchorConstraint, 'face' | 'target' | 'targetFace'>

/**
 * Direction along the axis (+1 / −1) in which a POSITIVE offset moves the face of the board:
 *  - target = furniture wall → into the furniture (left / bottom / back wall: +, the others: −),
 *  - target = board face     → into the board itself, i.e. its face retreats: away from a board it
 *    touches (prawa → lewa sąsiada: −) and recessed behind a face it is aligned with (przednia półki →
 *    przednia boku: − = cofnięta).
 * The raw axis value was used before, so right / top / front faces needed negative offsets.
 */
export function offsetDirection(c: AnchorFaces): 1 | -1 {
  const side = c.target.kind === 'furniture' ? FACE_INFO[c.targetFace][1] : FACE_INFO[c.face][1]
  return side ? -1 : 1
}

/** The board has anchors on both faces of the axis – its size there is set by the joints (stretched). */
export function isStretched(constraints: AnchorConstraint[], boardId: string, axis: Axis): boolean {
  const [lo, hi] = AXIS_FACES[axis]
  const faces = heldFaces(constraints, boardId)
  return faces.has(lo) && faces.has(hi)
}

/** Faces of a board held by joints: its own joints + the far side of two-sided joints made by other boards. */
export function heldFaces(constraints: AnchorConstraint[], boardId: string): Set<Face> {
  const faces = new Set<Face>()
  for (const c of constraints) {
    if (c.board === boardId) faces.add(c.face)
    else if (c.twoSided && c.target.kind === 'board' && c.target.id === boardId) faces.add(c.targetFace)
  }
  return faces
}

// ---- two-sided joints -------------------------------------------------------------------------------

/**
 * Can the joint be two-sided: a joint between two DIFFERENT boards whose faces look at each other on the
 * same axis (right ↔ left, top ↔ bottom, front ↔ back), and the axis is not the thickness of either of
 * them (both must be able to shrink / grow). Null = ok, otherwise the reason.
 */
export function twoSidedProblem(c: AnchorFaces & { board: string }, boards: Board[]): string | null {
  if (c.target.kind !== 'board') return 'Obustronne wiązanie łączy dwie płyty – nie ścianę mebla.'
  const id = c.target.id
  const a = boards.find((b) => b.id === c.board)
  const b = boards.find((o) => o.id === id)
  if (!a || !b || a.id === b.id) return 'Brak płyty docelowej.'
  const [axis, side] = FACE_INFO[c.face]
  if (FACE_INFO[c.targetFace][0] !== axis || FACE_INFO[c.targetFace][1] === side)
    return 'Ściany muszą być zwrócone do siebie (np. prawa ↔ lewa).'
  if (dimensionAxis(a.orientation, 'thickness') === axis || dimensionAxis(b.orientation, 'thickness') === axis)
    return 'Nie wzdłuż grubości płyty – obie płyty muszą móc się zwężać.'
  return null
}

/**
 * The two boards of a two-sided joint along its axis: `low` (its max face is joined) and `high` (its min
 * face is joined), and the faces: the joined ones and the far ones.
 */
export function twoSidedParts(c: AnchorConstraint): { axis: Axis; low: string; high: string } | null {
  if (c.target.kind !== 'board') return null
  const [axis, side] = FACE_INFO[c.face]
  return side === 1 ? { axis, low: c.board, high: c.target.id } : { axis, low: c.target.id, high: c.board }
}

/** Where the middle of the gap is between the far faces (0–1) in the current geometry. */
export function twoSidedBias(c: AnchorConstraint, boards: Board[]): number | null {
  const parts = twoSidedParts(c)
  if (!parts) return null
  const lo = boards.find((b) => b.id === parts.low)
  const hi = boards.find((b) => b.id === parts.high)
  if (!lo || !hi) return null
  const L = boardBounds(lo)
  const H = boardBounds(hi)
  const a = parts.axis
  const span = H.max[a] - L.min[a]
  if (span <= CONTACT_EPS) return null
  return Math.min(1, Math.max(0, ((L.max[a] + H.min[a]) / 2 - L.min[a]) / span))
}

/** Error [mm] of the balance of a two-sided joint (middle of the gap vs. bias of the span). */
export function twoSidedError(c: AnchorConstraint, boards: Board[]): number | null {
  const parts = twoSidedParts(c)
  if (!parts) return null
  const lo = boards.find((b) => b.id === parts.low)
  const hi = boards.find((b) => b.id === parts.high)
  if (!lo || !hi) return null
  const L = boardBounds(lo)
  const H = boardBounds(hi)
  const a = parts.axis
  return (L.max[a] + H.min[a]) / 2 - (L.min[a] + (c.bias ?? 0.5) * (H.max[a] - L.min[a]))
}

/** Makes a joint two-sided (keeping the current geometry: gap and bias from it) or one-sided again. */
export function setTwoSided(constraints: AnchorConstraint[], id: string, on: boolean, boards: Board[]): AnchorConstraint[] {
  return constraints.map((c) => {
    if (c.id !== id) return c
    if (!on) return { ...c, twoSided: undefined, bias: undefined }
    if (twoSidedProblem(c, boards)) return c
    const a = boards.find((b) => b.id === c.board)!
    const t = boards.find((b) => b.id === (c.target as { id: string }).id)!
    const gap = Math.abs(boardFaceValue(a, c.face) - boardFaceValue(t, c.targetFace))
    return { ...c, unit: undefined, offset: roundMm(gap), twoSided: true, bias: roundBias(twoSidedBias(c, boards) ?? 0.5) }
  })
}

export const roundBias = (v: number) => Number(v.toFixed(4))

/**
 * Coordinate [mm] the anchored face reaches at 100 % – the board then touches the furniture wall on the
 * far side (in the offset direction). A board hanging on one joint moves whole, so its size along the
 * axis is taken off; a stretched board moves only this face (at 100 % it would collapse – the panel
 * limits it before that). 0 % = the target plane, so raw offset = p · (limit − target).
 * The solver builds the same thing as a linear expression.
 */
export function freeLimitValue(c: AnchorFaces, board: Board, furniture: Furniture, stretched: boolean): number {
  const [axis, side] = FACE_INFO[c.face]
  const W = furnitureSize(furniture)[axis]
  const L = stretched ? 0 : boardSizeMm(board)[axis]
  return offsetDirection(c) > 0 ? W - (side === 0 ? L : 0) : side === 1 ? L : 0
}

/** Raw offset [mm] along the positive axis (face = target + raw), or null when the anchor is invalid. */
export function anchorRawOffset(
  c: AnchorConstraint,
  constraints: AnchorConstraint[],
  boards: Board[],
  furniture: Furniture,
): number | null {
  if (c.unit !== '%') return offsetDirection(c) * c.offset
  const board = boards.find((b) => b.id === c.board)
  const t = anchorTargetValue(c, boards, furniture)
  if (!board || t === null) return null
  const limit = freeLimitValue(c, board, furniture, isStretched(constraints, c.board, faceAxis(c.face)))
  return (c.offset / 100) * (limit - t)
}

/** Current error [mm] of an anchor (0 = satisfied), or null when it is invalid. */
export function anchorError(
  c: AnchorConstraint,
  boards: Board[],
  furniture: Furniture,
  constraints: AnchorConstraint[] = [c],
): number | null {
  if (!isAnchorValid(c, boards)) return null
  const board = boards.find((b) => b.id === c.board)!
  const t = anchorTargetValue(c, boards, furniture)!
  const raw = anchorRawOffset(c, constraints, boards, furniture)
  return raw === null ? null : boardFaceValue(board, c.face) - (t + raw)
}

/** Allowed range of a value (in the unit of the anchor / pair). */
export interface OffsetRange {
  min: number
  max: number
}

/**
 * Range of the offset (in the anchor's unit) that keeps the board inside the furniture, taken from the
 * current geometry: a board hanging on one joint moves whole (0 ≤ min face, max face ≤ furniture size);
 * a stretched board moves only this face, which cannot pass its other face (min. 1 mm board).
 * Negative values stay allowed as long as the board stays inside (e.g. a top overlapping the front).
 */
export function anchorRange(
  c: AnchorConstraint,
  constraints: AnchorConstraint[],
  boards: Board[],
  furniture: Furniture,
): OffsetRange | null {
  const board = boards.find((b) => b.id === c.board)
  const t = anchorTargetValue(c, boards, furniture)
  if (!board || t === null) return null
  if (c.twoSided) {
    // the gap: from touching to both boards 1 mm wide
    const parts = twoSidedParts(c)
    const lo = boards.find((b) => b.id === parts?.low)
    const hi = boards.find((b) => b.id === parts?.high)
    if (!parts || !lo || !hi) return null
    const span = boardBounds(hi).max[parts.axis] - boardBounds(lo).min[parts.axis]
    return { min: 0, max: roundMm(Math.max(0, span - 2 * MIN_BOARD_SIZE)) }
  }
  const [axis, side] = FACE_INFO[c.face]
  const W = furnitureSize(furniture)[axis]
  const stretched = isStretched(constraints, c.board, axis)
  let lo: number
  let hi: number
  if (stretched) {
    const other = boardFaceValue(board, oppositeFace(c.face))
    ;[lo, hi] = side === 0 ? [0, other - MIN_BOARD_SIZE] : [other + MIN_BOARD_SIZE, W]
  } else {
    const L = boardSizeMm(board)[axis]
    ;[lo, hi] = side === 0 ? [0, W - L] : [L, W]
  }
  let a: number
  let b: number
  if (c.unit === '%') {
    const free = freeLimitValue(c, board, furniture, stretched) - t
    if (Math.abs(free) < CONTACT_EPS) return { min: 0, max: 0 }
    a = ((lo - t) / free) * 100
    b = ((hi - t) / free) * 100
  } else {
    const d = offsetDirection(c)
    a = d * (lo - t)
    b = d * (hi - t)
  }
  return { min: roundMm(Math.min(a, b)), max: roundMm(Math.max(a, b)) }
}

/**
 * Switches the unit of an anchor keeping its effect (the same raw offset): mm ↔ % of the free space.
 * Nothing changes when there is no free space to count the percent of.
 */
export function setAnchorUnit(
  constraints: AnchorConstraint[],
  id: string,
  unit: OffsetUnit,
  boards: Board[],
  furniture: Furniture,
): AnchorConstraint[] {
  const c = constraints.find((o) => o.id === id)
  if (!c || (c.unit ?? 'mm') === unit || c.twoSided) return constraints
  const raw = anchorRawOffset(c, constraints, boards, furniture)
  const board = boards.find((b) => b.id === c.board)
  const t = anchorTargetValue(c, boards, furniture)
  if (raw === null || !board || t === null) return constraints
  let offset: number
  if (unit === '%') {
    const free = freeLimitValue(c, board, furniture, isStretched(constraints, c.board, faceAxis(c.face))) - t
    if (Math.abs(free) < CONTACT_EPS) return constraints
    offset = (raw / free) * 100
  } else {
    offset = offsetDirection(c) * raw
  }
  return constraints.map((o) => (o.id === id ? { ...o, unit, offset: roundMm(offset) } : o))
}

/** Tolerance [mm] of a satisfied anchor. */
export const ANCHOR_TOLERANCE = 0.01

/**
 * Ids of anchors that are not satisfied by the current geometry (or are invalid). The two anchors of a
 * centred board (see `centeredPairs`) are judged together – they are satisfied when the board sits in
 * the middle they define, even though neither face touches its own plane.
 */
export function violatedAnchors(constraints: AnchorConstraint[], boards: Board[], furniture: Furniture): string[] {
  const inPair = new Map<string, CenteredPair>()
  for (const pair of centeredPairs(constraints, boards)) {
    inPair.set(pair.min.id, pair)
    inPair.set(pair.max.id, pair)
  }
  return constraints
    .filter((c) => {
      const pair = inPair.get(c.id)
      const err = pair ? centeredPairError(pair, boards, furniture) : anchorError(c, boards, furniture, constraints)
      if (err === null || Math.abs(err) > ANCHOR_TOLERANCE * 2) return true
      if (!c.twoSided) return false
      const bal = twoSidedProblem(c, boards) ? null : twoSidedError(c, boards)
      return bal === null || Math.abs(bal) > ANCHOR_TOLERANCE * 2
    })
    .map((c) => c.id)
}

let counter = 0
export function newConstraintId(): string {
  counter += 1
  return typeof crypto !== 'undefined' && 'randomUUID' in crypto ? crypto.randomUUID() : `anchor-${Date.now()}-${counter}`
}

/**
 * Creates an anchor whose offset is taken from the CURRENT geometry – adding it never moves anything.
 */
export function createAnchor(
  board: Board,
  face: Face,
  target: AnchorTarget,
  targetFace: Face,
  boards: Board[],
  furniture: Furniture,
): AnchorConstraint {
  const t = targetFaceValue(target, targetFace, boards, furniture) ?? 0
  return {
    id: newConstraintId(),
    board: board.id,
    face,
    target,
    targetFace,
    offset: roundMm(offsetDirection({ face, target, targetFace }) * (boardFaceValue(board, face) - t)),
    restore: boardGeometry(board),
  }
}

/**
 * Anchor that PULLS the dependent board to the target: offset 0, so opposite faces (lewa → prawa) end up
 * touching and faces of the same side (lewa → lewa) aligned in one plane. Used by both ways of making a
 * joint – the chain in the scene and "Dodaj" in the panel; the offset is then changed in the panel.
 */
export function createPullingAnchor(
  board: Board,
  face: Face,
  target: AnchorTarget,
  targetFace: Face,
  boards: Board[],
  furniture: Furniture,
): AnchorConstraint {
  return { ...createAnchor(board, face, target, targetFace, boards, furniture), offset: 0 }
}

/**
 * Adds an anchor – a face can have only one anchor (like one constraint per side in ConstraintLayout),
 * so an existing anchor of the same board face is replaced.
 */
export function upsertAnchor(constraints: AnchorConstraint[], anchor: AnchorConstraint): AnchorConstraint[] {
  return [...constraints.filter((c) => !(c.board === anchor.board && c.face === anchor.face)), anchor]
}

/** Removes one constraint (e.g. its chain clicked in the scene). */
export function removeAnchor(constraints: AnchorConstraint[], id: string): AnchorConstraint[] {
  return constraints.filter((c) => c.id !== id)
}

/** Removes all constraints of a removed board (both as the constrained board and as the target). */
export function removeBoardConstraints(constraints: AnchorConstraint[], boardId: string): AnchorConstraint[] {
  return constraints.filter((c) => c.board !== boardId && !(c.target.kind === 'board' && c.target.id === boardId))
}

/**
 * After the user edited `updated` (position, dimensions, orientation – by the form or by dragging),
 * the offsets of its OWN anchors whose face actually moved are re-derived from the new geometry, so the
 * edit is kept (it becomes the new "margin"). Boards anchored to it are not touched here – they follow
 * it when the layout is solved.
 */
export function rederiveOffsets(
  constraints: AnchorConstraint[],
  previous: Board,
  updated: Board,
  boards: Board[],
  furniture: Furniture,
): AnchorConstraint[] {
  const others = boards.map((b) => (b.id === updated.id ? updated : b))
  return constraints.map((c) => {
    if (c.twoSided && (c.board === updated.id || (c.target.kind === 'board' && c.target.id === updated.id))) {
      const a = others.find((b) => b.id === c.board)
      const t = anchorTargetValue(c, others, furniture)
      if (!a || t === null) return c
      const bias = twoSidedBias(c, others)
      return { ...c, offset: roundMm(offsetDirection(c) * (boardFaceValue(a, c.face) - t)), bias: bias === null ? c.bias : roundBias(bias) }
    }
    if (c.board !== updated.id) return c
    if (previous.orientation === updated.orientation && Math.abs(boardFaceValue(previous, c.face) - boardFaceValue(updated, c.face)) < 1e-9) return c
    const t = anchorTargetValue(c, others, furniture)
    if (t === null) return c
    const raw = boardFaceValue(updated, c.face) - t
    if (c.unit === '%') {
      const free = freeLimitValue(c, updated, furniture, isStretched(constraints, c.board, faceAxis(c.face))) - t
      if (Math.abs(free) >= CONTACT_EPS) return { ...c, offset: roundMm((raw / free) * 100) }
    }
    return { ...c, unit: undefined, offset: roundMm(offsetDirection(c) * raw) }
  })
}

/** Positive overlap of the two boxes on the two axes other than `axis` (they share an area, not just an edge). */
export function overlapsAcross(a: Board, b: Board, axis: Axis): boolean {
  const ba = boardBounds(a)
  const bb = boardBounds(b)
  for (let i = 0; i < 3; i++) {
    if (i === axis) continue
    if (Math.min(ba.max[i], bb.max[i]) - Math.max(ba.min[i], bb.min[i]) <= CONTACT_EPS) return false
  }
  return true
}

/** One face-to-face contact: `board.face` touches `target.targetFace`. */
export interface Contact {
  board: Board
  face: Face
  target: AnchorTarget
  targetFace: Face
}

/**
 * Faces of `board` touching the furniture walls or faces of other boards (opposite faces with a
 * positive shared area). Furniture walls come first.
 */
export function findContacts(board: Board, boards: Board[], furniture: Furniture): Contact[] {
  const contacts: Contact[] = []
  for (const face of FACES) {
    const v = boardFaceValue(board, face)
    if (Math.abs(v - furnitureFaceValue(furniture, face)) < CONTACT_EPS) {
      contacts.push({ board, face, target: { kind: 'furniture' }, targetFace: face })
    }
  }
  for (const face of FACES) {
    const axis = faceAxis(face)
    const v = boardFaceValue(board, face)
    const other = oppositeFace(face)
    for (const o of boards) {
      if (o.id === board.id) continue
      if (Math.abs(v - boardFaceValue(o, other)) < CONTACT_EPS && overlapsAcross(board, o, axis)) {
        contacts.push({ board, face, target: { kind: 'board', id: o.id }, targetFace: other })
      }
    }
  }
  return contacts
}

/** The board's large surface is on this axis (its thickness axis) – otherwise the face is an edge. */
const isSurfaceAxis = (b: Board, axis: Axis) => dimensionAxis(b.orientation, 'thickness') === axis

/** True when the two boards are already joined on this axis (in either direction). */
function joinedOnAxis(constraints: AnchorConstraint[], a: string, b: string, axis: Axis): boolean {
  return constraints.some(
    (c) =>
      c.target.kind === 'board' &&
      faceAxis(c.face) === axis &&
      ((c.board === a && c.target.id === b) || (c.board === b && c.target.id === a)),
  )
}

const hasFaceAnchor = (constraints: AnchorConstraint[], boardId: string, face: Face) =>
  constraints.some((c) => c.board === boardId && c.face === face)

/**
 * "Przyklej": anchors every free face of `board` to the furniture wall / board face it touches.
 * `board` is always the dependent side. Faces that already have an anchor and pairs already joined on
 * the axis are skipped.
 */
export function attachToContacts(
  board: Board,
  constraints: AnchorConstraint[],
  boards: Board[],
  furniture: Furniture,
): AnchorConstraint[] {
  let result = constraints
  for (const c of findContacts(board, boards, furniture)) {
    if (hasFaceAnchor(result, board.id, c.face)) continue
    if (c.target.kind === 'board' && joinedOnAxis(result, board.id, c.target.id, faceAxis(c.face))) continue
    result = [...result, createAnchor(board, c.face, c.target, c.targetFace, boards, furniture)]
  }
  return result
}

/**
 * Anchors all touching faces of all boards (no longer offered in the UI – used to build test layouts).
 *  - a face touching a furniture wall is anchored to it,
 *  - two touching boards get ONE anchor; the dependent board is the one that touches with its EDGE the
 *    SURFACE of the other (a shelf between sides, a side under an overlaid top), otherwise the board
 *    added later.
 */
export function attachAllContacts(constraints: AnchorConstraint[], boards: Board[], furniture: Furniture): AnchorConstraint[] {
  let result = constraints
  const add = (board: Board, c: Contact) => {
    if (hasFaceAnchor(result, board.id, c.face)) return
    result = [...result, createAnchor(board, c.face, c.target, c.targetFace, boards, furniture)]
  }
  // furniture walls first – they are the root of every chain
  for (const b of boards) {
    for (const c of findContacts(b, boards, furniture)) if (c.target.kind === 'furniture') add(b, c)
  }
  boards.forEach((a, ia) => {
    for (const c of findContacts(a, boards, furniture)) {
      if (c.target.kind !== 'board') continue
      const targetId = c.target.id
      const ib = boards.findIndex((o) => o.id === targetId)
      const b = boards[ib]
      const axis = faceAxis(c.face)
      if (joinedOnAxis(result, a.id, b.id, axis)) continue
      const aEdge = !isSurfaceAxis(a, axis)
      const bEdge = !isSurfaceAxis(b, axis)
      const aDepends = aEdge !== bEdge ? aEdge : ia > ib
      if (aDepends) add(a, c)
      else add(b, { board: b, face: c.targetFace, target: { kind: 'board', id: a.id }, targetFace: c.face })
    }
  })
  return result
}

/**
 * Boards that follow the far furniture wall along `axis`: anchored to it directly, or anchored (as the
 * dependent board) to a board that follows it. The furniture may shrink below them – the solver moves
 * or shrinks them; the other boards still limit the minimum furniture size.
 */
export function boardsFollowingFurniture(constraints: AnchorConstraint[], axis: Axis): Set<string> {
  const onAxis = constraints.filter((c) => faceAxis(c.face) === axis)
  // a joint to the middle of two planes (`target2`) follows the wall when either plane does
  const farWall = (t: AnchorTarget | undefined, f: Face | undefined) => t?.kind === 'furniture' && !!f && FACE_INFO[f][1] === 1
  const set = new Set<string>(
    onAxis.filter((c) => farWall(c.target, c.targetFace) || farWall(c.target2, c.targetFace2)).map((c) => c.board),
  )
  const follows = (t: AnchorTarget | undefined) => t?.kind === 'board' && set.has(t.id)
  let grew = true
  while (grew) {
    grew = false
    for (const c of onAxis) {
      if ((follows(c.target) || follows(c.target2)) && !set.has(c.board)) {
        set.add(c.board)
        grew = true
      }
    }
  }
  return set
}

/** Human readable description of an anchor target face, e.g. "prawa ściana mebla" / "lewa · Płyta 3". */
export function targetLabel(c: AnchorConstraint, boards: Board[]): string {
  if (c.target2 && c.targetFace2) {
    const one = targetLabel({ ...c, target2: undefined, targetFace2: undefined }, boards)
    const two = targetLabel({ ...c, target: c.target2, targetFace: c.targetFace2, target2: undefined, targetFace2: undefined }, boards)
    return `środek: ${one} ↔ ${two}`
  }
  if (c.target.kind === 'furniture') return `${FACE_LABELS[c.targetFace]} ściana mebla`
  const id = c.target.id
  const name = boards.find((b) => b.id === id)?.name ?? '?'
  return `${name} · ${FACE_LABELS[c.targetFace]}`
}

// ---- handles (uchwyty) in the 3D scene ---------------------------------------------------------

/** A handle = one face of a board or of the furniture (start / end of a chain drawn in the scene). */
export interface HandleRef {
  owner: AnchorTarget
  face: Face
}

export const handleKey = (h: HandleRef) => `${h.owner.kind === 'furniture' ? 'F' : h.owner.id}:${h.face}`

const ownerBoardId = (h: HandleRef) => (h.owner.kind === 'board' ? h.owner.id : null)

/**
 * Why a chain from handle `from` to handle `to` cannot be made – or null when it can. Blocked are only
 * the connections that mean nothing:
 *  - faces on different axes, the same board on both ends, the furniture with itself,
 *  - a joint not involving the selected board (handles are shown for it),
 *  - exactly the same joint (that face → that face of that target) in either direction.
 * Anything else is allowed; what it does to the geometry is left to the solver (the board is pulled,
 * stretched or – if it cannot be done – the chain is shown red as unsatisfied).
 */
export function connectionProblem(
  from: HandleRef,
  to: HandleRef,
  selectedId: string | null,
  constraints: AnchorConstraint[],
): string | null {
  if (faceAxis(from.face) !== faceAxis(to.face)) return 'inna oś niż uchwyt startowy'
  const a = ownerBoardId(from)
  const b = ownerBoardId(to)
  if (a === null && b === null) return 'nie można związać mebla z meblem'
  if (a !== null && a === b) return 'to ta sama płyta'
  if (selectedId === null || (a !== selectedId && b !== selectedId)) return 'wiązanie musi dotyczyć zaznaczonej płyty'
  const [dep, tgt] = a !== null ? [from, to] : [to, from]
  const depId = ownerBoardId(dep)!
  const tgtId = ownerBoardId(tgt)
  const sameTarget = (t: AnchorTarget) =>
    tgtId === null ? t.kind === 'furniture' : t.kind === 'board' && t.id === tgtId
  const duplicate = constraints.some(
    (c) =>
      (c.board === depId && c.face === dep.face && sameTarget(c.target) && c.targetFace === tgt.face) ||
      (tgtId !== null &&
        c.board === tgtId &&
        c.face === tgt.face &&
        c.target.kind === 'board' &&
        c.target.id === depId &&
        c.targetFace === dep.face),
  )
  return duplicate ? 'takie wiązanie już istnieje' : null
}

/** Can a chain be drawn from handle `from` to handle `to`? See `connectionProblem`. */
export function canConnectHandles(from: HandleRef, to: HandleRef, selectedId: string | null, constraints: AnchorConstraint[]): boolean {
  return connectionProblem(from, to, selectedId, constraints) === null
}

/** Handle usable at all: while dragging – the start or a valid end; otherwise – it can start or end some chain. */
export function isHandleEnabled(
  h: HandleRef,
  all: HandleRef[],
  selectedId: string | null,
  constraints: AnchorConstraint[],
  dragFrom: HandleRef | null,
): boolean {
  if (dragFrom) return handleKey(dragFrom) === handleKey(h) || canConnectHandles(dragFrom, h, selectedId, constraints)
  return all.some((o) => canConnectHandles(h, o, selectedId, constraints) || canConnectHandles(o, h, selectedId, constraints))
}

/**
 * Joint created by a chain dropped on a handle: the owner of `from` is the dependent board (or the owner
 * of `to` when the chain starts at the furniture). The chain pulls the board to the target
 * (`createPullingAnchor`); an existing anchor of the same face is replaced.
 */
export function connectHandles(
  constraints: AnchorConstraint[],
  from: HandleRef,
  to: HandleRef,
  boards: Board[],
  furniture: Furniture,
): AnchorConstraint[] {
  const [dep, tgt] = from.owner.kind === 'board' ? [from, to] : [to, from]
  const depId = ownerBoardId(dep)
  const board = boards.find((b) => b.id === depId)
  if (!board || faceAxis(dep.face) !== faceAxis(tgt.face)) return constraints
  return upsertAnchor(constraints, createPullingAnchor(board, dep.face, tgt.owner, tgt.face, boards, furniture))
}

// ---- removing joints: back to the position from before ------------------------------------------

/** Board dimension lying along `axis`, or null for the thickness (never changed by a joint). */
function axisDimension(board: Board, axis: Axis): Exclude<BoardDimension, 'thickness'> | null {
  if (dimensionAxis(board.orientation, 'width') === axis) return 'width'
  if (dimensionAxis(board.orientation, 'height') === axis) return 'height'
  return null
}

const POSITION_AXES: (keyof BoardPosition)[] = ['x', 'y', 'z']

/**
 * After `removed` was deleted: if nothing else holds the board on that axis any more, its position and
 * size along the axis go back to the values from before that joint was made.
 */
export function restoreAfterRemoval(boards: Board[], removed: AnchorConstraint, remaining: AnchorConstraint[]): Board[] {
  const snapshot = removed.restore
  if (!snapshot) return boards
  const axis = faceAxis(removed.face)
  if (remaining.some((c) => c.board === removed.board && faceAxis(c.face) === axis)) return boards
  return boards.map((b) => {
    if (b.id !== removed.board) return b
    const next: Board = { ...b, position: { ...b.position, [POSITION_AXES[axis]]: snapshot.position[POSITION_AXES[axis]] } }
    const dim = axisDimension(b, axis)
    if (dim) next[dim] = snapshot[dim]
    return next
  })
}

/**
 * Removes the given joints and puts the boards they held back where they were (newest joint first, so
 * the snapshots unwind in the order they were made).
 */
export function removeAnchorsWithRestore(
  constraints: AnchorConstraint[],
  ids: string[],
  boards: Board[],
): { constraints: AnchorConstraint[]; boards: Board[] } {
  let cs = constraints
  let bs = boards
  for (const c of constraints.filter((c) => ids.includes(c.id)).reverse()) {
    cs = removeAnchor(cs, c.id)
    bs = restoreAfterRemoval(bs, c, cs)
  }
  return { constraints: cs, boards: bs }
}

// ---- what the joints of a board block -----------------------------------------------------------

/**
 * What the joints of one board fix (the offsets themselves are changed only in the panel):
 *  - a face with a joint cannot be moved in the scene,
 *  - one joint on an axis    → the board cannot be MOVED along it (it hangs on that joint),
 *  - joints on both faces    → the SIZE along that axis is fixed as well (the board is stretched).
 */
export interface BoardLocks {
  /** Faces of the board that have a joint of their own. */
  faces: Set<Face>
  /** Per axis: the position along it comes from a joint. */
  position: [boolean, boolean, boolean]
  /** Per axis: the size along it comes from joints on both faces. */
  size: [boolean, boolean, boolean]
  /**
   * Other boards hang on this one, so its orientation cannot be changed – it would swap the board's
   * faces between axes and turn their joints into something else entirely.
   */
  orientation: boolean
}

/** Do other boards depend on this one (is it the target of any joint)? */
export function hasDependents(constraints: AnchorConstraint[], boardId: string | null): boolean {
  return !!boardId && constraints.some((c) => c.target.kind === 'board' && c.target.id === boardId)
}

export function boardLocks(constraints: AnchorConstraint[], boardId: string | null): BoardLocks {
  const faces = boardId ? heldFaces(constraints, boardId) : new Set<Face>()
  const position: [boolean, boolean, boolean] = [false, false, false]
  const size: [boolean, boolean, boolean] = [false, false, false]
  for (const axis of [0, 1, 2] as Axis[]) {
    const [lo, hi] = AXIS_FACES[axis]
    position[axis] = faces.has(lo) || faces.has(hi)
    size[axis] = faces.has(lo) && faces.has(hi)
  }
  return { faces, position, size, orientation: hasDependents(constraints, boardId) }
}

/** Is this dimension of the board fixed by its joints? */
export function isDimensionLocked(locks: BoardLocks, board: Board, key: Exclude<BoardDimension, 'thickness'>): boolean {
  return locks.size[dimensionAxis(board.orientation, key)]
}

export const NO_LOCKS: BoardLocks = {
  faces: new Set(),
  position: [false, false, false],
  size: [false, false, false],
  orientation: false,
}

// ---- centred boards (two chains pulling the flat sides apart) -------------------------------------

/**
 * A board joined on BOTH flat sides (the faces of its thickness axis) to two opposite planes – e.g. a
 * divider chained to the left and to the right side of the carcass. The thickness cannot stretch, so the
 * two chains pull in opposite directions and the board ends up in the MIDDLE between them:
 *
 *     min + max = (targetMin + offsetMin) + (targetMax + offsetMax)
 *
 * so the board centre = middle of the two planes + the offset. The offset then pushes the board away
 * from that centre (not from one of the planes), and both anchors of the pair share it – the panel shows
 * them as one row with one value (see `centeredOffset` / `setCenteredOffset`).
 */
export interface CenteredPair {
  boardId: string
  axis: Axis
  /** Anchor of the min face (lewa / dolna / tylna) and of the max face (prawa / górna / przednia). */
  min: AnchorConstraint
  max: AnchorConstraint
}

/** Pairs of anchors that centre a board between two planes (only on the board's thickness axis). */
export function centeredPairs(constraints: AnchorConstraint[], boards: Board[]): CenteredPair[] {
  const pairs: CenteredPair[] = []
  for (const b of boards) {
    const axis = dimensionAxis(b.orientation, 'thickness')
    const [loFace, hiFace] = AXIS_FACES[axis]
    const own = constraints.filter((c) => c.board === b.id && isAnchorValid(c, boards))
    const min = own.find((c) => c.face === loFace)
    const max = own.find((c) => c.face === hiFace)
    if (min && max) pairs.push({ boardId: b.id, axis, min, max })
  }
  return pairs
}

/**
 * Unit of a centred pair:
 *  - 'mm' → the value is the distance of the board centre from the middle of the two planes, SIGNED
 *    along the axis (+ = right / up / front) – it is a direction, not a gap, so − is fine here,
 *  - '%'  → the value is the position of the board between the planes: 0 % = touching the min plane
 *    (lewa / dolna / tylna), 50 % = in the middle, 100 % = touching the max plane.
 */
export const centeredUnit = (pair: CenteredPair): OffsetUnit => pair.min.unit ?? 'mm'

/** Axis offset [mm] of each anchor of an mm pair – both carry the same one. */
const pairRaw = (pair: CenteredPair) =>
  offsetDirection(pair.min) * pair.min.offset + offsetDirection(pair.max) * pair.max.offset

/** Value of the pair in its unit (see `centeredUnit`). */
export const centeredOffset = (pair: CenteredPair) =>
  centeredUnit(pair) === '%' ? pair.min.offset : roundMm(pairRaw(pair) / 2)

/** Sets the value of the pair in its unit – both anchors of the pair carry it. */
export function setCenteredOffset(constraints: AnchorConstraint[], pair: CenteredPair, value: number): AnchorConstraint[] {
  const pct = centeredUnit(pair) === '%'
  return constraints.map((c) =>
    c.id === pair.min.id || c.id === pair.max.id ? { ...c, offset: pct ? value : roundMm(offsetDirection(c) * value) } : c,
  )
}

/** The two planes of a pair [min, max] (target faces without offsets) and the board thickness. */
function pairPlanes(pair: CenteredPair, boards: Board[], furniture: Furniture): { a: number; b: number; t: number } | null {
  const board = boards.find((o) => o.id === pair.boardId)
  const a = targetFaceValue(pair.min.target, pair.min.targetFace, boards, furniture)
  const b = targetFaceValue(pair.max.target, pair.max.targetFace, boards, furniture)
  if (!board || a === null || b === null) return null
  return { a, b, t: boardSizeMm(board)[pair.axis] }
}

/** min + max face coordinate the pair wants (the solver builds the same expression). */
function centeredWanted(pair: CenteredPair, boards: Board[], furniture: Furniture): number | null {
  const p = pairPlanes(pair, boards, furniture)
  if (!p) return null
  if (centeredUnit(pair) === '%') return 2 * p.a + 2 * (pair.min.offset / 100) * (p.b - p.a - p.t) + p.t
  return p.a + p.b + pairRaw(pair)
}

/** How far the centred board is from where the pair wants it (0 = satisfied). */
export function centeredPairError(pair: CenteredPair, boards: Board[], furniture: Furniture): number | null {
  const board = boards.find((b) => b.id === pair.boardId)
  const wanted = centeredWanted(pair, boards, furniture)
  if (!board || wanted === null) return null
  const [loFace, hiFace] = AXIS_FACES[pair.axis]
  return boardFaceValue(board, loFace) + boardFaceValue(board, hiFace) - wanted
}

/** Range of the pair value keeping the board between its two planes (± half the free gap / 0–100 %). */
export function centeredRange(pair: CenteredPair, boards: Board[], furniture: Furniture): OffsetRange | null {
  if (centeredUnit(pair) === '%') return { min: 0, max: 100 }
  const p = pairPlanes(pair, boards, furniture)
  if (!p) return null
  const half = roundMm(Math.max(0, (p.b - p.a - p.t) / 2))
  return { min: -half || 0, max: half }
}

/**
 * Switches the unit of a pair keeping the board where it is: shift s [mm] ↔ position p [%], where
 * s = (p − 50 %) · (gap − thickness). Nothing changes when the board does not fit between the planes.
 */
export function setCenteredUnit(
  constraints: AnchorConstraint[],
  pair: CenteredPair,
  unit: OffsetUnit,
  boards: Board[],
  furniture: Furniture,
): AnchorConstraint[] {
  if (centeredUnit(pair) === unit) return constraints
  const p = pairPlanes(pair, boards, furniture)
  const span = p ? p.b - p.a - p.t : 0
  if (span < CONTACT_EPS) return constraints
  const value = unit === '%' ? roundMm((pairRaw(pair) / 2 / span + 0.5) * 100) : roundMm((pair.min.offset / 100 - 0.5) * span)
  const retyped = constraints.map((c) => (c.id === pair.min.id || c.id === pair.max.id ? { ...c, unit } : c))
  return setCenteredOffset(retyped, { ...pair, min: { ...pair.min, unit }, max: { ...pair.max, unit } }, value)
}
